-- +goose Up
-- 教室: 全パラメータ(頭脳+身体+LOVE/面白)を伸ばす施設。学校と違いクールタイム制。
-- レガシー kyushitu.cgi 準拠(.tmp/legacy_spec/14_school_prof.md §2)。既存の汎用施設
-- パターン(facility='kyushitu' の content_items + DoFacilityAction)にそのまま乗せる。
-- effect=全パラメータ上昇+身体/頭脳パワー消費、price=受講料、use_interval_min=間隔(分)。
-- パラメータ上昇・金額・間隔はレガシー忠実。身体/頭脳消費のみ新プレイヤー基準にスケールダウン。
-- エッチ(etti)は除外方針、クレジット払い・体重減は省略(gymに倣う)。
INSERT INTO content_items (name, category, price, facility, use_interval_min, effect) VALUES
('フラフラダンス', '教室', 10000, 'kyushitu', 2,
 '[{"op": "add_param", "param": "kokugo", "amount": 1}, {"op": "add_param", "param": "suugaku", "amount": 1}, {"op": "add_param", "param": "rika", "amount": 1}, {"op": "add_param", "param": "syakai", "amount": 1}, {"op": "add_param", "param": "eigo", "amount": 1}, {"op": "add_param", "param": "ongaku", "amount": 1}, {"op": "add_param", "param": "bijutsu", "amount": 1}, {"op": "add_param", "param": "looks", "amount": 1}, {"op": "add_param", "param": "tairyoku", "amount": 1}, {"op": "add_param", "param": "kenkou", "amount": 1}, {"op": "add_param", "param": "speed", "amount": 1}, {"op": "add_param", "param": "power", "amount": 1}, {"op": "add_param", "param": "wanryoku", "amount": 1}, {"op": "add_param", "param": "kyakuryoku", "amount": 1}, {"op": "add_param", "param": "love", "amount": 1}, {"op": "add_param", "param": "omoshirosa", "amount": 1}, {"op": "add_param", "param": "energy", "amount": -2}, {"op": "add_param", "param": "nou_energy", "amount": -2}]'),
('フラダンス', '教室', 20000, 'kyushitu', 10,
 '[{"op": "add_param", "param": "looks", "amount": 10}, {"op": "add_param", "param": "tairyoku", "amount": 10}, {"op": "add_param", "param": "kenkou", "amount": 10}, {"op": "add_param", "param": "speed", "amount": 10}, {"op": "add_param", "param": "power", "amount": 10}, {"op": "add_param", "param": "wanryoku", "amount": 10}, {"op": "add_param", "param": "kyakuryoku", "amount": 10}, {"op": "add_param", "param": "energy", "amount": -5}]'),
('帝王学ミニ', '教室', 5000000, 'kyushitu', 50,
 '[{"op": "add_param", "param": "kokugo", "amount": 50}, {"op": "add_param", "param": "suugaku", "amount": 50}, {"op": "add_param", "param": "rika", "amount": 50}, {"op": "add_param", "param": "syakai", "amount": 50}, {"op": "add_param", "param": "eigo", "amount": 50}, {"op": "add_param", "param": "ongaku", "amount": 50}, {"op": "add_param", "param": "bijutsu", "amount": 50}, {"op": "add_param", "param": "looks", "amount": 50}, {"op": "add_param", "param": "tairyoku", "amount": 50}, {"op": "add_param", "param": "kenkou", "amount": 50}, {"op": "add_param", "param": "speed", "amount": 50}, {"op": "add_param", "param": "power", "amount": 50}, {"op": "add_param", "param": "wanryoku", "amount": 50}, {"op": "add_param", "param": "kyakuryoku", "amount": 50}, {"op": "add_param", "param": "love", "amount": 50}, {"op": "add_param", "param": "omoshirosa", "amount": 500}, {"op": "add_param", "param": "energy", "amount": -20}, {"op": "add_param", "param": "nou_energy", "amount": -20}]'),
('帝王学', '教室', 10000000, 'kyushitu', 100,
 '[{"op": "add_param", "param": "kokugo", "amount": 100}, {"op": "add_param", "param": "suugaku", "amount": 100}, {"op": "add_param", "param": "rika", "amount": 100}, {"op": "add_param", "param": "syakai", "amount": 100}, {"op": "add_param", "param": "eigo", "amount": 100}, {"op": "add_param", "param": "ongaku", "amount": 100}, {"op": "add_param", "param": "bijutsu", "amount": 100}, {"op": "add_param", "param": "looks", "amount": 100}, {"op": "add_param", "param": "tairyoku", "amount": 100}, {"op": "add_param", "param": "kenkou", "amount": 100}, {"op": "add_param", "param": "speed", "amount": 100}, {"op": "add_param", "param": "power", "amount": 100}, {"op": "add_param", "param": "wanryoku", "amount": 100}, {"op": "add_param", "param": "kyakuryoku", "amount": 100}, {"op": "add_param", "param": "love", "amount": 100}, {"op": "add_param", "param": "omoshirosa", "amount": 100}, {"op": "add_param", "param": "energy", "amount": -30}, {"op": "add_param", "param": "nou_energy", "amount": -30}]');

-- +goose Down
DELETE FROM content_items WHERE facility = 'kyushitu';
